[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["lib"]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.5.17"
legacy = true
fs_permissions = [
    { access = "read", path = "./broadcast"}, 
    { access = "read", path = "./script/upgrades/dependencies.json"}
]

libraries = [
########################################################################################
# There's a foundry bug that occurs when trying to verify libraries in sourcify.
# The verification fails for the library and it aborts the rest of the verifications
# for all contracts in that script run.
# The way to get around this is by running the script once and then statically
# specifying the libraries in the config file.
# However there is no way to specify the libraries per network, so we have to
# keep them here commented. If we don't comment them we run the risk of 
# accidentally linking the wrong libraries on the wrong network.
# Baklava:
#     "lib/mento-core/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0x3e2cc57f83093Ce1Ee03482c1590E3B5f4225bd7",
#     "lib/mento-core/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol:AddressSortedLinkedListWithMedian:0x99EDce8143FF8AeFA1fBB6C2103B349Add2B9519",
# Alfajores:
#     "lib/mento-core/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0xbdBEE70764261b753cb9C59d5d6bdE96fe7d0234",
#     "lib/mento-core/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol:AddressSortedLinkedListWithMedian:0xa8010E684104D6684f7552C4107592e43Ed390Bd",
# Mainnet: TBD
########################################################################################
]

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[profile.integration]
no_match_contract = "RandomTest"
match_contract = "Integration"

[rpc_endpoints]
celo_mainnet="${CELO_MAINNET_RPC_URL}"
baklava="${BAKLAVA_RPC_URL}"
alfajores="${ALFAJORES_RPC_URL}"
