[profile.default]
out = "out"
test = "test"
script = "script"
libs = ["lib"]
auto_detect_solc = true
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
legacy = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./out" },
    { access = "read", path = "./data" },
    { access = "read", path = "./script/upgrades/dependencies.json" },
]
via_ir = true


# There's a bug that occurs when trying to verify libraries in sourcify, on testnets.
# The verification fails for the library and it aborts the rest of the verifications
# for all contracts in that script run.
# The way to get around this is by running the script once, have it fail and then
# specify the libraries under the specific network here
#
# However, it is important to note that the first time a deployment is run on a network
# we will have to rerun a deployment after all libraries are deployed and linked here.
# If not then the metadata of contracts deployed **before** the libraries were added,
# contracts that do not require the libraries, will still have their bytecode different
# because of the metadata hash, and the verification will fail. This is because
# the metadata of a contract will contain the statically linked libraries during compilation
# irrespective of whether the contract uses them or not.


[profile.baklava-deployment]
libraries = [
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0x3e2cc57f83093Ce1Ee03482c1590E3B5f4225bd7",
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol:AddressSortedLinkedListWithMedian:0x99EDce8143FF8AeFA1fBB6C2103B349Add2B9519",
]

[profile.alfajores-deployment]
libraries = [
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0x2F0F7686fFFEfc3C266403Ad600035581deaedff",
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol:AddressSortedLinkedListWithMedian:0x29B1B5e05217c751038861aF2C77494EAB10A257",
]

[profile.celo-deployment]
libraries = [
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0x6200F54D73491d56b8d7A975C9ee18EFb4D518Df",
    "lib/mento-core-2.0.0/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol:AddressSortedLinkedListWithMedian:0xED477A99035d0c1e11369F1D7A4e587893cc002B",
]

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[profile.integration]
no_match_contract = "RandomTest"
match_contract = "Integration"

[rpc_endpoints]
celo = "${CELO_RPC_URL}"
baklava = "${BAKLAVA_RPC_URL}"
alfajores = "${ALFAJORES_RPC_URL}"

