[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["lib"]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.5.17"
legacy = true
fs_permissions = [
    { access = "read", path = "./broadcast"}, 
    { access = "read", path = "./script/upgrades/dependencies.json"}
]

# libraries = [
#     "lib/mento-core/contracts/common/linkedlists/AddressLinkedList.sol:AddressLinkedList:0x3e2cc57f83093Ce1Ee03482c1590E3B5f4225bd7"
# ]

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[profile.integration]
no_match_contract = "RandomTest"
match_contract = "Integration"

[rpc_endpoints]
celo_mainnet="${CELO_RPC_URL}"
baklava="${BAKLAVA_RPC_URL}"
