/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IBreaker, IBreakerInterface } from "../IBreaker";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newSortedOracles",
        type: "address",
      },
    ],
    name: "SortedOraclesUpdated",
    type: "event",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "rateFeedID",
        type: "address",
      },
    ],
    name: "getCooldown",
    outputs: [
      {
        internalType: "uint256",
        name: "cooldown",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "rateFeedID",
        type: "address",
      },
    ],
    name: "shouldReset",
    outputs: [
      {
        internalType: "bool",
        name: "resetBreaker",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "rateFeedID",
        type: "address",
      },
    ],
    name: "shouldTrigger",
    outputs: [
      {
        internalType: "bool",
        name: "triggerBreaker",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBreaker__factory {
  static readonly abi = _abi;
  static createInterface(): IBreakerInterface {
    return new utils.Interface(_abi) as IBreakerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBreaker {
    return new Contract(address, _abi, signerOrProvider) as IBreaker;
  }
}
